<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FinanceWallet.Api\FinanceWallet.Api.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Bootstrapper\FinanceWallet.Bootstrapper.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Admin\FinanceWallet.Modules.Admin.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Audit\FinanceWallet.Modules.Audit.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.ExternalAccounts\FinanceWallet.Modules.ExternalAccounts.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Identity\FinanceWallet.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Ledger\FinanceWallet.Modules.Ledger.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Messaging\FinanceWallet.Modules.Messaging.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Notifications\FinanceWallet.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Risk\FinanceWallet.Modules.Risk.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Security\FinanceWallet.Modules.Security.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Transactions\FinanceWallet.Modules.Transactions.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Modules.Wallets\FinanceWallet.Modules.Wallets.csproj" />
    <ProjectReference Include="..\..\src\FinanceWallet.Shared\FinanceWallet.Shared.csproj" />
  </ItemGroup>

</Project>
